#https://lukelowrey.com/use-github-actions-to-publish-nuget-packages/
name: Publish Packages

on:
   # push:
   #    branches: [ master ]
   workflow_dispatch:
jobs:
   build:
      runs-on: ubuntu-latest
      env:
        HUSKY: 0
      steps:
         - uses: actions/checkout@v2
         - name: Setup .NET
           uses: actions/setup-dotnet@v1
           with:
              dotnet-version: 7.0.x
         - name: Restore dependencies
           run: dotnet restore cicd.sln
         - name: Build
           run: dotnet build cicd.sln --configuration Release --no-restore
         - name: Test
           run: dotnet test cicd.sln --configuration Release --no-build --verbosity normal
         - name: Publish InfiniteEnumFlags
           uses: alirezanet/publish-nuget@v3.0.0
           with:
              PROJECT_FILE_PATH: src/InfiniteEnumFlags.csproj
              INCLUDE_SYMBOLS: true
              NUGET_KEY: ${{secrets.NUGET_API_KEY}}
 
