name: Build Pull Requests

on:
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      HUSKY: 0
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 7.0.x
    - name: Restore dependencies
      run: dotnet restore cicd.sln
    - name: Build
      run: dotnet build cicd.sln -c Release --no-restore
    - name: Test
      run: dotnet test cicd.sln -c Release --no-build --verbosity normal
